name 'appserver'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures appserver'
long_description 'Installs/Configures appserver'
version '0.1.0'
